### ISSUE TITLE
URL not being generated correctly.

### ISSUE THREAD

**Issue by kyranb** [czim/laravel-paperclip#13]
Using the following path:

`'path' => 'Foo/:attachment/:id/:variant/:hash/',`

creates the following url:

`/Foo/:attachment/:id/original/:hash/:variant/filename.filextention`

It seems that an additional `original` is being appended, no matter what the `variant` (and where it is not given in the path).

I'll look into this further, but just leaving my findings here.

**Comment by czim** [comment]
Thanks for the heads-up. I know there are some things different (or simply wrong) with the path interpolation currently. The way paperclips works right now is to take the path without filename and extension, and append different directories + the filename/ext for different variants.

So it does not use the `:variant` placeholder, or at least not the way you'd expect it to.

I'm super short on time, but I'm hoping to rewrite this logic to allow it to use path interpolation in a more consistent way -- that would solve this issue (and several others aswell).

As always, any help is appreciated! :]

**Comment by czim** [comment]
I've released version `2.5.0` for Laravel 5.5+. This should resolve the issue.

Do note that this brings quite a few breaking changes, including in the config.

To get the same (desired) result, you'd now probably set `path.original` to:

`Foo/:attachment/:id/:variant/:hash/:filename`

Let me know if that helps!
