### ISSUE TITLE
Is there a method to get only the relative path?

### ISSUE THREAD

**Issue by brunodevel** [czim/laravel-paperclip#17]
I need to make some files private in order to authorize the user first before downloading them.

Is there a method to get only the file relative path (without the app URL), without changing the `paperclip.storage.base-urls` config?

Thanks in advance.

**Comment by czim** [comment]
In `2.*` versions, you can call `path()` on the attachment (so `$model->image->path()` to get the relative path to the (original) file.

Alternatively, you could get the URL, and remove the base path config value from it:

```php
$baseLength   = strlen(config('paperclip.storage.base-urls.paperclip'));
$relativePath = substr(0, $baseLength, $model->image->url());
```
