### ISSUE TITLE
Duplicate record

### ISSUE THREAD

**Issue by lostcause** [czim/laravel-paperclip#18]
Hi,

I have an issue with duplicating records for models which have attachements. 
I tried
_(this was taken from a previous project which used Stapler)_

```
$newImage = new ProductImage;
$newImage->image->setUploadedFile($oldImage->image->path());
```

But that does not work, as setUploadedFile is not expecting a string as a parameter.
How could I go about copying the file (to the correct path, of course) when duplicating the record?

Thank you.

**Comment by czim** [comment]
Your best bet is to make an instance of `\Symfony\Component\HttpFoundation\File\UploadedFile` (Laravel's UploadedFile extends this, so you can use that aswell), or make an `\SplFileInfo` instance, or, if all else fails, an instance that implements `Czim\FileHandling\Contracts\Support\RawContentInterface` (such as `Czim\FileHandling\Support\Content\RawContent`).

Any of the above can be passed into the `$newImage->image` property (*not* directly in the `setUploadedFile()` method!). 

If you really want to use the `setUploadedFile()` method, instances of `Czim\FileHandling\Storage\File\RawStorableFile` or `Czim\FileHandling\Storage\File\SplFileInfoStorableFile` would work too. I recommend just using the `$newImage->image` property though, this is the norm and easier to use, aswell.
