### ISSUE TITLE
How I can change filename? 

### ISSUE THREAD

**Issue by anton-kuzmenko** [czim/laravel-paperclip#2]
I want use a hash or maybe model slug for file name.
How I can change filename of uploaded file?

In config I use:
`'base-path' => ':class_name/:attribute',`

**Comment by nevedimko** [comment]
Also if I use 
`$this->hasAttachedFile('image', ['url' => '/:class_name/:attachment/:style/:hash.:extension', 'storage' => 's3']);`

Then I will get an url like `/Product/images/original/80ccd59a719f2767156694923e74dcea96baa78e9220c697e1e8dddaeef7bd8f.png/original/test.png`

**Comment by czim** [comment]
Just a note (and apology): Sorry, I am not ignoring this, just very busy at this hectic time of year. I will get back to this and take a look, soon.

**Comment by rbruhn** [comment]
I'm running into this exact problem. If the files have spaces in the names, such as an image, it's not showing on the page. Would be nice to use the before hook to set the name for storage. Or, use the mutator in the model (if one exists) to set the name of the stored file.

**Comment by czim** [comment]
I've released version `2.5.0` for Laravel 5.5+. This should resolve the issue.

Do note that this brings quite a few breaking changes, including in the config.

Using `:class_name/:attachment/:style/:hash.:extension` for a path should now work.
