### ISSUE TITLE
Does not find a disk to save

### ISSUE THREAD

**Issue by freecod** [czim/laravel-paperclip#25]
https://github.com/czim/laravel-paperclip/blob/41bbcfe079a0ca34c8ec6a9e0bc7de0158721575/src/Handler/FileHandlerFactory.php#L36
https://github.com/czim/laravel-paperclip/blob/41bbcfe079a0ca34c8ec6a9e0bc7de0158721575/src/Handler/FileHandlerFactory.php#L39

this code does not see disk settings from config/filesystems.php, because disks are specified in "disks" key and settings are available as config("filesystems.disks.{$ disk}.driver");

Laravel 5.5.33

**Comment by czim** [comment]
Good catch!

This should not affect Paperclip's ability to find a disk to save to (this is configured in the `paperclip.php` config). 

I have fixed this, and it will become part of a new release version later on.

**Comment by czim** [comment]
`2.5.3` released, which has this fixed.
