### ISSUE TITLE
Serializing models with attachment (for Redis)

### ISSUE THREAD

**Issue by rossbearman** [czim/laravel-paperclip#27]
I'm currently in the process of replacing Stapler with Paperclip on a site. Getting it working at a basic level has been pretty painless, with the old images being displayed correctly by Paperclip without much configuration. However with Paperclip installed, any attempt to serialize a model (for example using `Cache::rememberForever`) fails, with the error "Serialization of 'Closure' is not allowed".

I noticed that the `attachedFiles` property includes the Laravel container, and this contains the only closures I can find on this model, under `attachedFiles > handler > processor > stategyFactory > container`.

Is there a way to get around this that I'm missing? Thanks.

**Comment by czim** [comment]
I hear you. This was always the problem with Stapler as well, and that has remained the same with this package. I have no immediate solution for this. For my own purposes, the 'work-around' I've used is to serialize only as FQN+ID pairs and re-lookup the models on unserialization (similar to how Laravel itself handles this using the `SerializesModels` trait.

**Comment by rossbearman** [comment]
I believe it's caused by the use of the `$container` property in czim/file-handling's `VariantStrategyFactory`.

**Comment by rossbearman** [comment]
I think we're going to stick with Stapler for the time being, as being unable to cache models is a deal breaker for performance, storing just the ID and requesting it from the database on each hit wouldn't be a viable solution.

Given Stapler has been abandoned we'll probably need to migrate at some point (or come up with a different solution) and if this is unlikely to be fixed I think we'll have to look into splitting the attachments into their own models and just pulling the URLs model from that into an array when the cache needs to be warmed.

It might be worth noting in the readme that Paperclip isn't compatible with Laravel's caching system.

**Comment by czim** [comment]
I do want to look into this, but I haven't the time until next weekend. If you are in a hurry, sticking with Stapler is the way to go for now.

**Comment by rossbearman** [comment]
No problem, Stapler works for now (the application is already live and heavily used), but we're aware that with it no longer being supported a migration is inevitable, especially as fixes are often required on every major Laravel patch.

Thanks for your time.

**Comment by czim** [comment]
I found some time and wrote a quick fix. It won't win any beauty prices, but it allows for serialization without bumping into any of file-handling's closures. Version `2.5.4` should fix that. If it doesn't, please let me know.

**Comment by rossbearman** [comment]
That's great, thank you very much, I'll try and test this tomorrow.

**Comment by rossbearman** [comment]
Hi czim, that seems to be working fine now, thanks again.

I think the only adjustment we need to make now is implementing a custom variant strategy so that we can force the JPEG quality to `100`. We were using `convert_options` for this previously and without it it seems to introduce a lot of JPEG artefacts with any resize operations. Unless there is a way to force this through the config instead?

**Comment by rossbearman** [comment]
Ah, that wasn't necessary, after reading the code,we just had to change `convert_options` in the options array into `convertOptions`.

Might be worth mentioning that in this bit of the "Differences with Stapler" section:

>One major difference is that the convert_options configuration settings are no longer available. Conversion options are now handled at the level of the variant strategies.

>You can set them per attachment configuration, or modify the variant strategy to use a custom global configuration.

**Comment by czim** [comment]
Thanks for the heads-up!
Hmm, considering the Stapler-compatibility, I think I should also support `convert_options`. 

Plus, I think it's also time to update the documentation to tell the whole story, not rely in Stapler's documentation any longer. That, and the migration guide that's been in the issues for a while...
