### ISSUE TITLE
`before` callback doesn't work with s3 storage

### ISSUE THREAD

**Issue by anton-kuzmenko** [czim/laravel-paperclip#3]
`$hook = $this->getConfigValue($type);`

`$hook` is null

**Comment by czim** [comment]
@anton-kuzmenko I've looked into this, but cannot see any problems with this (yet). The `before` hook is called regardless of the storage driver used.

I also do not understand your code example. In what context are you trying to call this code?
Is this from withing the context of a before closure/function?

You can set up a before hook in a model constructor like so:
```
    $this->hasAttachedFile('image', [
        'before' => function ($attachment) { /* Do something here */ },
    ]);
```
The (first and only) parameter passed into the hook closure/method is the instance of the attachment (`Czim\Paperclip\Attachment\Attachment`), so you can call any (public) method on that to try and do what you want.

If you think something is broken, please help me out and provide more specific information -- a full code example, for instance.
