### ISSUE TITLE
Paperclip storing wrong file on s3 instead of actual file.

### ISSUE THREAD

**Issue by alankarglobant** [czim/laravel-paperclip#32]
In documentation related to the difference with the stapler, there is a line saying 

> Another difference is that this package does not handle (s3) storage.
> All storage is performed through Laravel's storage solution.

So, does paperclip store the files on the s3 bucket?
I have tried this with s3 bucket option with configuration by setting `disk` => `s3` under `config/paperclip.php` file it is storing the wrong file on the bucket. 

Basically I am exporting excel and putting that on s3, but when I am executing the code it is creating excel at `storage/app` folder (The actual excel which holds the exported data. ) and creating new file under `storage/app/public/` which holds the path of the actual exported excel file which is under `storage/app`  and the excel which is created under `public` folder is being sent to the s3 bucket.

[Tracker_2018-11-01_ef22781f-675b-4eae-a0ae-760c8d6aa752.xlsx](https://github.com/czim/laravel-paperclip/files/2538009/Tracker_2018-11-01_ef22781f-675b-4eae-a0ae-760c8d6aa752.xlsx)

**Comment by czim** [comment]
Paperclip defers all storage logic to Laravel. Any storage 'disk' that you configure for Laravel, should work as-is for paperclip. So S3 is still supported, through Laravel -- but it is no longer *built in* like it was with Stapler.

As for your issue, I don't fully understand what file is stored 'wrong'. Can you explain further what's going wrong? Can you give the code or a code snippet, and the paperclip configuration you use?

**Comment by alankarglobant** [comment]
Thank you for your feedback Below are the details of configuration and explanation related to the issue I am facing. 

Configuration:
From filesystems.php

```
 'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => env('APP_URL') . '/storage',
            'visibility' => 'public',
        ],

        'paperclip' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL') . '/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_REGION'),
            'bucket' => env('S3_BUCKET'),
            'url' => env('AWS_URL'),
        ],
]
```

from paperclip: 
```
    'storage' => [

        // The Laravel storage disk to use.
        //'disk' => 'paperclip',
        'disk' => 's3',

        // Per disk, the base URL where attachments are stored at
        'base-urls' => [
            'paperclip' => config('app.url') . '/paperclip',
        ],
    ],
```
I have set storage option for paperclip is `s3`.  The problem is I am facing is the file is created with a name that I have passed but in that content is not the same that I have exported instead it is having the file path.  
[Uploading Tracker_2018-11-02_443ec3fb-e821-4b86-a7e3-ff9b95c30bf2.xlsx…]( Check this file )

**Comment by alankarglobant** [comment]
One more example I would like to give you is I am creating a PDF at location `storage/temp` 
and uploading it on the AWS S3 bucket. But it is also not working. 

The function which I am using for saving the file to the bucket is.

```
    /**
     * Handle createing a new FileUpload model and uploading the file to S3
     *
     * @param  File $file
     * @param  String $remotePath
     */
    public function uploadFile($file, $remotePath)
    {
        $fileUploadModel = new FileUpload(["filePath" => $remotePath]);
        $fileUploadModel->remote = $file;
        $fileUploadModel->save();
        $fileUploadModel->secureUrl();

        return $fileUploadModel;
    }

```

`$file` = "/var/www/html/storage/temp/Project-Plan.pdf",
`$remotePath` = "remotes/plans/30/Project-Plan.pdf"

Here are the snippets from the FileUpload Model. 

````

<?php namespace App\Models;

use Config;
use Czim\Paperclip\Contracts\AttachableInterface;
use Czim\Paperclip\Model\PaperclipTrait;
use Eloquent;
use Illuminate\Database\Eloquent\SoftDeletes;

class FileUpload extends Eloquent implements AttachableInterface
{
    use PaperclipTrait;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $table = 'remote_storage';

    protected $fillable = ['remote', 'remote_file_name'];

    public function __construct($attributes = [])
    {
        if (isset($attributes['filePath'])) {
            $this->hasAttachedFile('remote', [
                "path" => $attributes["filePath"],
            ]);
        } else {
            $this->hasAttachedFile('remote', []);
        }

        parent::__construct($attributes);
    }

    public function getUrlAttribute()
    {
        return $this->secureUrl();
    }

    public function secureUrl($options = [], $time = "+24 hours")
    {
        if (array_key_exists("remotePath", $options)) {
            $remotePath = $options["remotePath"];
        } else {
            $remotePath = $this->remote->path();
        }
        $this->secure_url = $this->getSecureUrl($remotePath, $time);
        return $this->secure_url;
    }

    public function getSecureUrl($remotePath, $time = "+24 hours")
    {
        $s3 = \App::make('aws')->createClient('s3');
        $command = $s3->getCommand('GetObject', [
            'Bucket' => env('S3_BUCKET'),
            'Key' => $remotePath,
        ]);

        $request = $s3->createPresignedRequest($command, $time);
        return (string) $request->getUri();
    }

    public function doesFileExist($options = array())
    {
        $s3 = \App::make('aws')->createClient('s3');
        $remotePath = $options["remotePath"];

        return $s3->doesObjectExist(Config::get('readylab_s3.bucket'), $remotePath);
    }

}
````
Now, the problem here is I am able to see the PDF on S3 bucket but it is corrupted and it is not opening via S3 URL. But if I download the PDF before uploading to the S3 it is opening correctly.

**Comment by czim** [comment]
Let's see. You're storing an instance of File (according to your docblock) directly into the `remote` attachment property:

```php
<?php
        $fileUploadModel->remote = $file;
```

What kind of class is this `File`? 

The behaviour here (storing a URL or path to a file, rather than its contents) is what I expect when the URL, as a string, is stored directly on the `remote` attribute. That is intended behaviour, albeit different from Stapler.

In most cases, usage involves storing a Laravel `UploadedFile` instance. Storing files or content directly is a slightly different. case.
The readme has an example of this, under the header [Setting attachments without uploads](https://github.com/czim/laravel-paperclip#setting-attachments-without-uploads).

Does that help?

**Comment by alankarglobant** [comment]
Thank you for your valuable feedback. It helps me to save the file details in the database and it is saving correct details as well.

I have made the below changes;

````
        $filePath = storage_path("app/$fileName");
        $fileUpload = FileUpload::create([
            'remote_file_name' => $remotePath,
            'remote' => new \SplFileInfo($filePath),   //
        ]);

        $fileUpload->secureUrl(['remotePath' => $remotePath], '+5minutes');
````

 
But. then the file will be upload to the S3 automatically or do I have to upload it on S3 manually? ( I mean do I need to write the separate code for the same or the this plugin's Laravel storage class will upload it to s3)

**Comment by czim** [comment]
I recommend you first attempt to get S3 storage using Laravel to work. If that works, simply selecting the storage disk in the `paperclip.php` configuration file should work too -- and in that case you do not have to do any manual uploading! Paperclip was made precisely to automate this, so that would defeat its purpose.

For more information on Laravel storage, see these documentation pages:
- [S3 driver prerequisites](https://laravel.com/docs/5.7/filesystem#driver-prerequisites)
- [Laravel File Storage](https://laravel.com/docs/5.7/filesystem)

**Comment by alankarglobant** [comment]
I seriously thank you for your quick and valuable feedbacks. I have managed to save the correct file to the S3 disk. But, having little confusion. 
Option 1:
```
        $fileUpload = FileUpload::create([
            'filePath' => $remotePath,
            'remote' => new \SplFileInfo(storage_path("app/$fileName")),
        ]);
```

Option 2:
```
        $fileUpload = new FileUpload(['filePath' => $remotePath]);
        $fileUpload->remote_file_name = $remotePath;
        $fileUpload->remote =  new \SplFileInfo($filePath);
        $fileUpload->save();

```

In the model, I have set the `path` attributes in options.  Some basic snippets from the model.

```
<?php namespace App\Models;

use Config;
use Czim\Paperclip\Contracts\AttachableInterface;
use Czim\Paperclip\Model\PaperclipTrait;
use Eloquent;
use Illuminate\Database\Eloquent\SoftDeletes;

class FileUpload extends Eloquent implements AttachableInterface
{
    use PaperclipTrait;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $table = 'remote_storage';

    protected $fillable = ['remote', 'remote_file_name'];

    public function __construct($attributes = [])
    {
        if (isset($attributes['filePath'])) {
            $this->hasAttachedFile('remote', [
                "path" => $attributes["filePath"],
            ]);
        } else {
            $this->hasAttachedFile('remote', []);
        }

        parent::__construct($attributes);
    }
 
   /// REST OF THE CODE 
}
````

When I am using option 1 it is using an automated path to store on the S3 bucket like. `App/Models/FileUpload/000/008/274/remote/original/Tracker_2018-11-05_c16b3523-5325-49b6-abc9-53cda110fa0f.xlsx"` 

From above this I have understood that, in an option 1 `create` method is not calling the constructor hence the `path` is not having correct value.  In option 2 as I am creating the new instance of model it is setting the attribute value that I have passed as an argument.  

Is it the correct behaviour?

**Comment by czim** [comment]
I think you found the source of the problem. 

The way you're using the `path` Paperclip attachment setting does not make sense to me. What is the aim of using it this way, and making it dependent on an attribute value (at construction)?

In normal cases, the `path` is a placeholder string, that is filled in on storage actions. It should therefore be something like this: `':class/:id_partition/:attribute/:variant/:filename'`. On writes, this would get interpolated into a full path, like `'App/Models/FileUpload/000/008/274/remote/original/somefilename.xlsx'`.

Is there a reason the path value is dynamic and based on an Eloquent attribute?
I expect that this may well be the cause of some unexpected behaviour. In addition to your current problem, if a model is constructed once with one path value, and later with another, it will not point to the same file, potentially making a file uploaded earlier inaccessible at a later date.

**Comment by alankarglobant** [comment]
Thank you for clearing my doubts. Yes, the `path` value is dynamic because we are using this same model for different files imported or exported in our application. 

Thank you so much for your quick feedback, which helps me to resolve my issue.

**Comment by czim** [comment]
Glad to hear you got it fixed. No problem, happy to help.
