### ISSUE TITLE
Variant data not being written to database

### ISSUE THREAD

**Issue by flyingL123** [czim/laravel-paperclip#35]
I'm not sure what I'm missing, but based on the documentation it seemed that if I have an attachment named `image`, I could add a column called `image_variants`, and that should be populated with JSON data about the attachments that were created. Here is my setup:

```
$this->hasAttachedFile('image', [
	'variants' => [
		'thumbnail' => [
			'auto-orient' => [],
			'resize' => ['dimensions' => '300', 'convert_options' => ['quality' => 80]],
		],
		'zoom' => [
			'auto-orient' => [],
			'resize' => ['dimensions' => '1280'],
		],
	],
	'attributes' => [
		'variants' => true
	]
]);
```

You can see I am including the `attributes.variants` key and setting it `true`. However, after saving, the file is put on s3 along with the variants, all the other database fields are populated, but the `image_variants` field is simply `[]`.

What am I doing wrong here?

**Comment by czim** [comment]
I'm pretty certain that the variants data is only written on a 'necessary-only' basis. So unless you're generating different extensions and/or mimetypes for your variants, you may expect the `variants` field to be an empty array.

The main purpose of the variants field is as an alternative for:
- As an alternative for 'hard-coding' the expected extension or mimetype for a variant in the attachment configuration, or
- For supporting cases where a variant may be rendered with a different extension or mimetype for different records of a model.

**Comment by flyingL123** [comment]
Interesting. I was hoping it would contain the image dimensions for the generated files. I guess I will have to save those separately myself.

**Comment by czim** [comment]
Ah, nope. That's not the way it works, I fear.

If you want to record information like that somewhere, you could write your own file handling variant strategy (see documentation & code for [czim/file-handling](https://github.com/czim/file-handling).

**Comment by flyingL123** [comment]
@czim but with a custom file handling variant, how can I access the Eloquent model for the file being processed? I need access to the model instance so I can write to one of it's attributes, right? Is this possible?

**Comment by flyingL123** [comment]
For future reference, this was pretty simple. I just pass the model to my custom strategy via the config array:

```
'zoom' => [
    'store-dimensions' => ['model' => $this]
]
```
Then it can be accessed in the model via `$this->options['model'];`.
