### ISSUE TITLE
base URL should not be necessary for s3 storage

### ISSUE THREAD

**Issue by flyingL123** [czim/laravel-paperclip#36]
Using Laravel 5.6, I was finding that I needed to include my bucket name in the `AWS_URL` environment in order for the `Storage` facade to generate the correct URLs. For example, if:
```
AWS_URL=https://s3.amazonaws.com
AWS_BUCKET=mybucket
```
The resulting URL from `Storage::url('file.txt')`, will not include the bucket name:

`https://s3.amazonaws.com/file.txt`

If I hardcode the bucket name to the url, it works:

```
AWS_URL=https://s3.amazonaws.com/mybucket
```
But it seems like I shouldn't have to do that. So, another option that works, as seen on [this thread](https://laracasts.com/discuss/channels/general-discussion/bucket-name-not-appearing-in-s3-url), is to completely remove `AWS_URL` from the config. This works and results in `Storage::url('file.txt')` returning the subdomain version of the url, which is fine, correctly including the bucket name:

```
https://mybucket.s3.amazonaws.com/file.txt
```

The problem is, this set up results in paperclip throwing an error:

```
RuntimeException with message 'Could not determine base URL for storage disk 'paperclip'
```

Is there any way to fix this and make the two settings play nicely together?

**Comment by czim** [comment]
I just released `2.6.1`, which fixes this issue. It now uses `Storage::disk($disk)->url('.')` as a fallback for the other configuration options. Updating should resolve your issue.
