### ISSUE TITLE
Using outside of laravel

### ISSUE THREAD

**Issue by szonov** [czim/laravel-paperclip#37]
Now paperclip works in lumen with adding several global helpers.
Is it possible to make it working without laravel, just with  Capsule?
Generally, it is eloquent (database) + filesystems, It should not depends on whole laravel.

**Comment by czim** [comment]
I've not developed Paperclip to be used either in Lumen or entirely outside of a framework. I'm not against it, of course, just did not develop it for that purpose. I'd actually recommend using the file-handling package separately, as that is designed to be used outside of Laravel context, Paperclip is basically a wrapper around that package, and to use Eloquent.

I'm open to PRs that remedy this, of course!
