### ISSUE TITLE
Default URL

### ISSUE THREAD

**Issue by lostcause** [czim/laravel-paperclip#4]
Hi,

Laravel Stapler had a config key for the  default_url, 
```
        $this->hasAttachedFile('foo', [
            'styles' => [
                'thumbnail' => '100x100',
                'large' => '300x300'
            ],
            'url' => '/system/:attachment/:id_partition/:style/:filename',
            'default_url' => '/:attachment/:style/missing.jpg'
        ]);
```

which was returned if no image was found. I tried it in Paperclip also, but it doesn't seem to work. Is there a way to set this up, maybe on a model basis?

**Comment by czim** [comment]
This functionality is not in paperclip, you're right. I intentionally left it out.

My argument against this is that it's not a good solution. To have a transparent fallback to a default image from within the attachment handling logic incorrectly suggests that an attachment was set, even when it never was. To receive a null for a URL when there is no attachment set, is much clearer and more natural behavior.

Default attachments (that is, fallback values for missing attachments) are something that IMO should be handled by presenters (or their like). It's not information about what was stored for a model -- but about what is to be presented when nothing was stored.

If you have no workable solution that could do this with presenter logic, do tell -- maybe we can think of another approach. Or if you have a good reason why this functionality should be included, I'm always open to further discussion.

**Comment by lostcause** [comment]
No need for it, I just  was used to it and thought it was missing in the docs :)

Thank you for the answer!
