### ISSUE TITLE
Animated gif not supported by resize strategy

### ISSUE THREAD

**Issue by roboticsexpert** [czim/laravel-paperclip#40]
when resizing animated gif images, output gif file is not animated

**Comment by czim** [comment]
This has to do with the [czim/file-handling Resizer](https://github.com/czim/file-handling/blob/master/src/Support/Image/Resizer.php) and its [resize strategy](https://github.com/czim/file-handling/blob/master/src/Variant/Strategies/ImageResizeStrategy.php).

For now, I'd recommend writing your own (resize) strategy that handles the animated gif resize how you want it. If there is a fix that will allow resizing of animated gifs that also supports the current resize functionality, I'd be obliged if you'd submit it as a PR to the czim/file-handling package.
