### ISSUE TITLE
CLI option to (re)generate only one resize of a specific attachment

### ISSUE THREAD

**Issue by JJWesterkamp** [czim/laravel-paperclip#42]
Hi!

Would it be possible to have an option to only refresh a single resize of an attachment? Let's say I have this model `App\Models\MyModel`  that already has one attachment `"image"` and 2 existing resizes `"resize-1"` and `"resize-2"`.

If I now add a new resize `"resize-3"` to my model config it would be nice to be able to only generate the images for the newly added resize, whereas `php artisan paperclip:refresh "App\Models\MyModel" --attachments image` seems to regenerate all resizes for attachment `"image"`.

I'd imagine a CLI option `"--attachment"` (singular, so that there can be no ambiguity regarding which attachment we're talking about). Then an additional option `"--resizes"` could take the list of resizes to refresh:

```
$ php artisan paperclip:refresh "App\Models\MyModel" --attachment image --resizes resize-3
```
Is this a viable idea? Or does this already exist in some way, and am I missing something?

Thanks!

**Comment by czim** [comment]
Looks like a fine idea, and should not be hard to implement. The main thing it needs is a console option to indicate the relevant type; I should look into whether it's already possible to reprocess individual variants, but even adding that should not cause any problems.

**Comment by czim** [comment]
Added in versions `2.7.2` and `2.6.3`. Good suggestion, thanks!
