### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by diggersworld** [czim/laravel-paperclip#45]
Will you be adding support for Laravel 6?

**Comment by czim** [comment]
Yes, I'm working on it. I have a bunch of packages to work through, but Paperclip is on the list.

**Comment by czim** [comment]
I've tested the package with PHPUnit 7, 8 and Laravel 6.0 test fixtures, and it passes all the tests. It appears that version 2.7 is ready for Laravel 6.0.

If this is not the case (which would mean that the tests are lacking!), please let me know!
