### ISSUE TITLE
Is there a way to timeout remote URL fetches?

### ISSUE THREAD

**Issue by iredmedia** [czim/laravel-paperclip#49]
I'm getting some really long requests from a specific provider, and it's causing me some headaches. 

The offending line where the request hangs is here:
`Czim\FileHandling\Support\Download\UrlDownloader::downloadToTempLocalPath`

Is there any way in laravel-paperclip to set a timeout on UrlDownloads?

**Comment by czim** [comment]
I did not build in an easy way to do this, though I believe that would've been a good idea. The UrlDownloader is part of the `czim/filehandling` package, and uses raw cURL in an attempt to limit its dependencies. I think that can be handled better, but that's a feature for a later date.

For now, you can create a workaround for your problem by extending the `Czim\FileHandling\Support\DownloadUrlDownloader` yourself. Override the `downloadToTempLocalPath` method to handle the download as you please.

Then add a binding to your own service provider (f.i. your `AppServiceProvider@register`) like so:
```php
$this->app->singleton(\Czim\FileHandling\Contracts\Support\UrlDownloaderInterface::class, YourExtendedUrlDownloader::class);
```

That's the easiest workaround/hack I can think of, as it is.
