### ISSUE TITLE
A method to check if the file is set?

### ISSUE THREAD

**Issue by ProGM** [czim/laravel-paperclip#5]
Is there an official way to check if the attachment was set?

`$myModel->attachment` is always set, even if the file does not exists. It would be cool something like `$myModel->attachment->exists()`.

Since I can't find it, I'm using `!$myModel->attachment->size()`, but it's not very good, since it fails with 0-sized files

**Comment by czim** [comment]
The following method exists on the Attachment class. Would this do what you need?

```php
/**
     * Returns whether this attachment actually has a file currently stored.
     *
     * @return bool
     */
    public function isFilled()
    {
        return ! empty($this->originalFilename());
    }
```

`$attachment->isFilled()`

**Comment by daniel-de-wit** [comment]
Personally I like @ProGM suggestion for `->exists()`. It aligns with the Eloquent method for checking a model. Maybe add an alias @czim?

**Comment by czim** [comment]
It does have a much better ring to it. If you can make a PR for this with a `@deprecated` tag on the original `isFilled()` method, I'd be much obliged. Otherwise, I can do it myself, but it will be a while.
