### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by jbajou** [czim/laravel-paperclip#51]
Hello,

Will this package be compatible Laravel 7.x ? Any estimated delivery date ?

Thanks

**Comment by czim** [comment]
It is likely that the latest version already works in Laravel 7; if you haven't tried it, please do.

If it does not, there will be a compatible release soon. No exact ETA, but likely this weekend.

**Comment by jbajou** [comment]
Tried it indeed.
It is just a dependency version issue.

```
Conclusion: don't install symfony/http-foundation 5.1.x-dev|keep czim/laravel-paperclip 2.7.4|keep symfony/http-foundation v4.4.5|install czim/laravel-paperclip 2.7.4
```
Thanks for the fast reply and the great work on this package.

**Comment by czim** [comment]
There was also a change in an Eloquent method signature that broke things. 3.0.1 is the first paperclip version that'll work with Laravel 7, the file handling dependency has also been upgraded.
