### ISSUE TITLE
File goes missing at times after upload

### ISSUE THREAD

**Issue by raj-uimatic** [czim/laravel-paperclip#52]
At times while uploading the file goes missing and an exception is thrown. This only happens sometimes and I cannot replicate error on will.

**Error log says** 
`(Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/root/public\" does not exist at /root/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:116)`

**Stack Trace**
```
#0 /root/vendor/czim/file-handling/src/Support/Content/MimeTypeHelper.php(37): Symfony\\Component\\HttpFoundation\\File\\MimeType\\MimeTypeGuesser->guess('/root/w...')
#1 /root/vendor/czim/file-handling/src/Storage/File/StorableFileFactory.php(127): Czim\\FileHandling\\Support\\Content\\MimeTypeHelper->guessMimeTypeForPath('/root/w...')
#2 /root/vendor/czim/file-handling/src/Storage/File/StorableFileFactory.php(94): Czim\\FileHandling\\Storage\\File\\StorableFileFactory->makeFromFileInfo(Object(Illuminate\\Http\\UploadedFile), 'D458D0B1-9F2D-4...', NULL)
#3 /root/vendor/czim/laravel-paperclip/src/Model/PaperclipTrait.php(129): Czim\\FileHandling\\Storage\\File\\StorableFileFactory->makeFromAny(Object(Illuminate\\Http\\UploadedFile))
#4 /root/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1394): App\\Vendors\\VendorGalleryMedia->setAttribute('vendor_image', Object(Illuminate\\Http\\UploadedFile))
#5 /root/app/Http/Controllers/Admin/VendorImagesController.php(115): Illuminate\\Database\\Eloquent\\Model->__set('vendor_image', Object(Illuminate\\Http\\UploadedFile))
#6 [internal function]: App\\Http\\Controllers\\Admin\\VendorImagesController->update(Object(Illuminate\\Http\\Request), '400')

```

**Filesystems.php settings are as below**

```
local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ],
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
        'upload' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'visibility' => 'public',
        ],
        'backups' => [
			'driver' => 'local',
			'root' => storage_path('backups'), 
		],
        
      's3' => [
            'driver' => 's3',
            'key'    => env('S3_APP_KEY'),
            'secret' => env('S3_SECRET_KEY'),
            'region' => env('S3_REGION'),
            'bucket' => env('S3_BUCKET'),
            'visibility' => 'public',
            'options' => [
                'CacheControl' => 'max-age=315360000, no-transform, public',
            ],
        ]
```

**Comment by czim** [comment]
This can happen for a great variety of reasons. The upload may have failed, the disk may be full, there may be an error with the source data (especially if it needs to be downloaded, for instance).. I know the error is not very helpful, but that is because the problem happened somewhere before that point, and it is not easy to know what, after it happens.

Try some debugging techniques once you can consistently reproduce it -- or try different sources, copying the file locally first, etc. -- and let me know how it goes.

**Comment by raj-uimatic** [comment]
The basic debugging like storage and file checks etc all are done and everything is in place. 
The tricky thing is, this 2-3 years old code and worked perfectly fine. Things that have changed are PHP 7.1 to 7.3 bump and laravel version upgrade.

One slightly relevant thing I found was that the ImageMagick library was missing although the PHP extension was installed. I will observe for the next day or two and post updates.
