### ISSUE TITLE
Saving new Image from url causes Exception

### ISSUE THREAD

**Issue by AhmedAli-Ibtikar** [czim/laravel-paperclip#58]
My Saving Code 
```
$order_image = ModelName::create( [
     'order_id' => $object->order_id,      
     'image' => $url_string,
     'default' => $object->default,
     'visible' => $object->visible,
     'priority' => $object->priority
] );
```

![Screenshot from 2020-05-11 12-22-08](https://user-images.githubusercontent.com/57864861/81551687-8edb7500-9382-11ea-9108-687f5ee6c6fc.png)

**Comment by czim** [comment]
This can happen for many different reasons. Full disks, corrupt files, incompatible file formats, wrong extensions, etc.. these can all result in Imagine not being able to open the (tmp) file.

Can you try the strategy described in the documentation [for dealing with saving files that are not uploads](https://github.com/czim/laravel-paperclip#setting-attachments-without-uploads)? If that doesn't work, low-level debugging may be required.

One thing you can try is (temporarily) editing the Imagine class file, and outputting information about the /tmp/ file right before the exception. If you dump its contents or other properties of it, you may get more useful information to find out what's going wrong.

**Comment by AhmedAli-Ibtikar** [comment]
@czim this is an issue on my server it worked perfectly after running it on other two servers without any problem thank you for your time

**Comment by pratikshap31** [comment]
@czim @AhmedAli-Ibtikar 

Do you know how to fix it?
I am getting the same error for some images.
