### ISSUE TITLE
Processed variant ignores Orientation EXIF

### ISSUE THREAD

**Issue by kimchirichie** [czim/laravel-paperclip#63]
Problem: upload an image with correct orientation EXIF data -> the processed variant orientation is not applied. 

Model `Photo.php`:
```
    public function __construct(array $attributes = [])
    {
        $this->hasAttachedFile('image', [
            'variants'  => [
                Variant::make('thumb')->steps([
                    AutoOrientStep::make(),
                    ResizeStep::make()->width(480)->height(270)->crop(), // = '480x270#'
                ]),
                Variant::make('small')->steps([
                    AutoOrientStep::make(),
                    ResizeStep::make()->width(480), // = '480x'
                ]),
                Variant::make('medium')->steps([
                    AutoOrientStep::make(),
                    ResizeStep::make()->width(640), // = '640x'
                ]),
                Variant::make('large')->steps([
                    AutoOrientStep::make(),
                    ResizeStep::make()->width(1280), // = '1280x'
                ]),
            ],
            'url' => config('services.cdn.image_not_found'),
        ]);

        parent::__construct($attributes);
    }
```

Problematic photos:
- [original w/ Rotate 90 CW](https://oap-staging-assets-bucket.s3.us-east-2.amazonaws.com/Photo/428835/image/original/P1040114.JPG) & [result](https://oap-staging-assets-bucket.s3.us-east-2.amazonaws.com/Photo/428835/image/large/P1040114.JPG)

- [original w/ Rotate 90 CW](https://oap-staging-assets-bucket.s3.us-east-2.amazonaws.com/Photo/428833/image/original/P1040112.JPG) & [result](https://oap-staging-assets-bucket.s3.us-east-2.amazonaws.com/Photo/428833/image/large/P1040112.JPG)

using a [meta tag tool](http://metapicz.com) i was able to verify these photos had the correct orientation EXIF data.

Is there a possibility that this is a bug?

**Comment by kimchirichie** [comment]
after careful study and inspection I have been able to resolve this issue.

```
Variant::make('large')->steps([
        AutoOrientStep::make(), 
        ResizeStep::make()->width(480)->height(270)->crop(), // = '480x270#'
]),
```
will result in 
```
[
  "resize" => array:2 [
    "dimensions" => "480x270#"
    "convertOptions" => []
  ]
  "auto-orient" => array:1 [
    "quiet" => false
  ]
]
```
which applies the resize before auto-orient. As stated in the document, auto-orient must come before resize step. To fix this, simply reverse the order of the way it is applied. Viz.

```
Variant::make('large')->steps([
        ResizeStep::make()->width(480)->height(270)->crop(), // = '480x270#'
        AutoOrientStep::make(), 
]),
```
which will result in 
```
[
  "auto-orient" => array:1 [
    "quiet" => false
  ]
  "resize" => array:2 [
    "dimensions" => "480x270#"
    "convertOptions" => []
  ]
]
```

**Comment by czim** [comment]
Thanks for this update and your careful testing! Version `3.2.2` fixes this. 👍
