### ISSUE TITLE
AutoOrientStep not working in heroku

### ISSUE THREAD

**Issue by kimchirichie** [czim/laravel-paperclip#65]
For the past 3 days, I have been stuck with a rather frustrating problem. `AutoOrientStep` works on local but not on any heroku deployed servers.

Here are all the things I made sure to do:
- locally mimic heroku environment (copy env vars + use `heroku local`)
- composer cache to be cleared using `composer cacheclear` before reinstalling all composer packages
- ensure composer package versions are identical locally and remotely
- ensure php versions are identical locally and remotely

Suspicious things:
- no failures logged on heroku servers.
- identical commit, identical configurations launched on an EC2 instance works as expected
- `ResizeStep` works. only `AutoOrientStep` does not.

This is not likely something to do with the library, but some configuration issue. i would like to document this in case anyone else has experienced this.

I have exhausted my debugging options. Any debugging suggestions would be appreciated.

Photo Model:
```
...
public function __construct(array $attributes = [])
{
    $this->hasAttachedFile('image', [
        'variants'  => [
            Variant::make('thumb')->steps([
                AutoOrientStep::make(),
                ResizeStep::make()->width(480)->height(270)->crop(), // = '480x270#'
            ]),
            Variant::make('small')->steps([
                AutoOrientStep::make(),
                ResizeStep::make()->width(480), // = '480x'
            ]),
            Variant::make('medium')->steps([
                AutoOrientStep::make(),
                ResizeStep::make()->width(640), // = '640x'
            ]),
            Variant::make('large')->steps([
                AutoOrientStep::make(),
                ResizeStep::make()->width(1280), // = '1280x'
            ]),
            Variant::make('xlarge')->steps([
                AutoOrientStep::make(),
                ResizeStep::make()->width(2560), // = '2560x'
            ]),
        ],
        'url' => config('services.cdn.image_not_found'),
    ]);

    parent::__construct($attributes);
}
...
```

A Queued Laravel Job:
```
...
// process variants
$file = app(StorableFileFactory::class)->makeFromUrl($fileUrl);
$photo->image = $file;
$photo->save();
...
```

**Comment by kimchirichie** [comment]
after another long day, I've been able to track the source to the following `function_exists('exif_read_data')` evaluating to `false`. this is part of `czim/file-handling` in `OrientationFixer::fixImage`.

**Comment by kimchirichie** [comment]
Finally some momentum. after a quick search heroku seems to not have exif extension enabled by default.
https://stackoverflow.com/questions/16224488/how-to-get-the-exif-php-extension-working-on-heroku

I have added it into my `composer.json`

```
"require": {
        ...,
        "ext-exif":"*",
        ...,
}
```

Thank god I found this. It has been on my mind the whole year.

**Comment by kimchirichie** [comment]
this problem had me through `czim/file-handling` + `czim/laravel-paperclip`. I now have a deeper understanding of both packages and additional appreciation for each. learned lots!

thanks for coming to my ted talk. now closing this issue. happy new year.

**Comment by czim** [comment]
Thanks a lot for your issue and mainly for your detailed follow-up reports on it! This will definitely help others who may run into this. 👍
