### ISSUE TITLE
Variant ImageOptimizationStrategy to convert to webp

### ISSUE THREAD

**Issue by jbajou** [czim/laravel-paperclip#77]
Hello!

Great fan of the package, as always. It's the first time I'd like to use `ImageOptimizationStrategy` though, and I find myself having problems understanding how.

So far, I added the following to the `config/paperclip.php` file:

```
'variants' => [

        'aliases' => [
            ...other variants... 
            'optimization'    => \Czim\FileHandling\Variant\Strategies\ImageOptimizationStrategy::class,
        ],
```

On the model:
```
public function __construct(array $attributes = [])
    {
        $this->hasAttachedFile('media', [
            'variants' => [
                'variant-name' => [
                   'optimization'
               ]
            ],
        ]);
   }
```

Obviously, no optimisation is happening. My ultimate goal is to generate some webp files for a couple of variants. Any guidance would be much appreciated.

Thanks in advance!

**Comment by czim** [comment]
Hey! The`variant-name` is an example name. In your case, if you want to set configuration details for your strategy, you'd do it like this:

```php
public function __construct(array $attributes = [])
    {
        $this->hasAttachedFile('media', [
            'variants' => [
                'optimization' => [
                    'your-setting' => 'your value',
               ]
            ],
        ]);
   }
```

Adding configuration is entirely optional though.
This would work too:

```php
        $this->hasAttachedFile('media', [
            'variants' => [
                'optimization',
            ],
        ]);
   }
```

Or, alternatively:

```php
        $this->hasAttachedFile('media', [
            'variants' => [
                Variant::make('optimization')
            ],
        ]);
   }
```

**Comment by jbajou** [comment]
Hey! Thanks for the swift reply! `variant-name` is one of our variants (we have 10), I just redacted it for readability/focus on the issue.

The `perform()` method of the `ImageOptimizationStrategy` is never called, that's why I'm thinking it's not working for me so far.
Also, how can I configure this to use webP for the conversion ? Only through the `extension` key ?

Thanks again

**Comment by czim** [comment]
Yup, you have to manually tell it that the `extension` should be webp. The actual conversion is done by your logic, but Paperclip needs to be told what to make of it for that variant -- if no extension is specified, it'll keep the extension of the original.

**Comment by jbajou** [comment]
So I finally got the time to look into this further. It looks like the constructor of the `ImageOptimizationStrategy` is not called in case you also use `dimensions` in your variant, like this:
```
'webp'  => [
    'auto-orient' => [
        "quiet" => false
    ],
    'dimensions'  => '250x332#',
    'optimize' => [],
],
```

If I remove the `dimensions` key, the constructor is called. What strikes me is that the output of the above variant is indeed a webP (having the same weight of its jpeg counterpart), but the ImageOptimizationStrategy is not called in that case.

Do you have any idea why @czim ?

**Comment by czim** [comment]
Sorry to respond so late -- and without being much help. I don't know of any reason why the optimize step isn't called upon in that scenario. It definitely should, unless some hard error occurs in the preceding steps. I assume that you cannot change the order?

**Comment by jbajou** [comment]
Hello @czim ! Thanks for the feedback.
I finally managed to make it work, here it is for posteriority:

In the model:
```
'variants'   => [
    // Original size, webP optimized
                'webp'                     => [
                    'auto-orient' => [
                        "quiet" => false
                    ],
                    'optimize'    => [],
                ],
],
    // Extensions
            'extensions' => [
                'webp'                     => 'webp',
]
```

It turns out the `ImageOptimizationStrategy` is called, even with a resize such as:
```
'my-webp-variant' => [
                    'auto-orient' => [
                        "quiet" => false
                    ],
                    'resize'      => [
                        'dimensions' => '500x664#',
                        'quality'    => 100,
                    ],
                    'optimize'    => [],
                ],
```
I believe the issue was around the `resize` vs `dimensions` without being 100% sure, I can't remember.

Thanks!
